-- CreateTable
CREATE TABLE `ACTIVITY_LOG` (
    `log_id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` INTEGER NOT NULL,
    `tender_id` INTEGER NULL,
    `bid_id` INTEGER NULL,
    `action_type` VARCHAR(191) NOT NULL,
    `entity_type` VARCHAR(191) NOT NULL,
    `entity_id` INTEGER NULL,
    `old_values` TEXT NULL,
    `new_values` TEXT NULL,
    `ip_address` VARCHAR(191) NULL,
    `user_agent` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`log_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BID` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `tender_id` INTEGER NOT NULL,
    `bidder_org_id` INTEGER NOT NULL,
    `submitted_by` INTEGER NOT NULL,
    `status_id` TINYINT UNSIGNED NOT NULL,
    `bid_amount` DECIMAL(15, 2) NOT NULL,
    `discount_percentage` DECIMAL(5, 2) NULL DEFAULT 0,
    `execution_period_days` INTEGER NULL,
    `technical_proposal` TEXT NULL,
    `financial_proposal` TEXT NULL,
    `submitted_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `evaluated_at` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BID_DOC_TYPE` (
    `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `type_name` VARCHAR(191) NOT NULL,
    `type_name_ar` VARCHAR(191) NOT NULL,
    `is_required` BOOLEAN NOT NULL DEFAULT false,
    `description` TEXT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BID_DOCUMENT` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bid_id` INTEGER NOT NULL,
    `uploaded_by` INTEGER NOT NULL,
    `doc_type_id` TINYINT UNSIGNED NOT NULL,
    `doc_name` VARCHAR(191) NOT NULL,
    `file_url` VARCHAR(191) NOT NULL,
    `uploaded_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BID_EVALUATION` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bid_id` INTEGER NOT NULL,
    `committee_member_id` INTEGER NOT NULL,
    `score` DECIMAL(5, 2) NOT NULL,
    `comments` TEXT NULL,
    `evaluated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BID_GUARANTEE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bid_id` INTEGER NOT NULL,
    `guarantee_type` VARCHAR(191) NOT NULL,
    `guarantee_number` VARCHAR(191) NOT NULL,
    `amount` DECIMAL(15, 2) NOT NULL,
    `issuing_bank` VARCHAR(191) NULL,
    `issue_date` DATE NULL,
    `expiry_date` DATE NULL,
    `attachment_url` VARCHAR(191) NULL,
    `is_validated` BOOLEAN NOT NULL DEFAULT false,
    `validated_at` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BID_STATUS` (
    `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `status_name` VARCHAR(191) NOT NULL,
    `status_name_ar` VARCHAR(191) NOT NULL,
    `is_final` BOOLEAN NOT NULL DEFAULT false,
    `reason` TEXT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BID_STATUS_HISTORY` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bid_id` INTEGER NOT NULL,
    `old_status_id` TINYINT UNSIGNED NOT NULL,
    `new_status_id` TINYINT UNSIGNED NOT NULL,
    `changed_by` INTEGER NOT NULL,
    `reason` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `COMMITTEE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `tender_id` INTEGER NOT NULL,
    `committee_type` TINYINT UNSIGNED NOT NULL,
    `formed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `COMMITTEE_EVALUATION` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bid_id` INTEGER NOT NULL,
    `committee_id` INTEGER NOT NULL,
    `avg_score` DECIMAL(5, 2) NOT NULL,
    `final_comments` TEXT NULL,
    `final_decision` VARCHAR(191) NOT NULL,
    `decided_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `COMMITTEE_MEMBER` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `committee_id` INTEGER NOT NULL,
    `user_id` INTEGER NOT NULL,
    `role_in_committee` VARCHAR(191) NOT NULL,
    `assigned_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `COMMITTEE_TYPE` (
    `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `committee_name` VARCHAR(191) NOT NULL,
    `committee_name_ar` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CONTRACT` (
    `contract_id` INTEGER NOT NULL AUTO_INCREMENT,
    `tender_id` INTEGER NOT NULL,
    `bid_id` INTEGER NOT NULL,
    `contract_number` VARCHAR(191) NOT NULL,
    `contract_value` DECIMAL(15, 2) NOT NULL,
    `start_date` DATE NULL,
    `end_date` DATE NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'DRAFT',
    `attachment_url` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `CONTRACT_contract_number_key`(`contract_number`),
    PRIMARY KEY (`contract_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NOTIFICATION` (
    `notification_id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` INTEGER NOT NULL,
    `tender_id` INTEGER NULL,
    `bid_id` INTEGER NULL,
    `notification_type` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `message` TEXT NOT NULL,
    `is_read` BOOLEAN NOT NULL DEFAULT false,
    `action_url` VARCHAR(191) NULL,
    `sent_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `read_at` DATETIME(3) NULL,

    PRIMARY KEY (`notification_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORGANIZATION` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type_id` TINYINT UNSIGNED NOT NULL,
    `status_id` TINYINT UNSIGNED NOT NULL,
    `org_name` VARCHAR(191) NOT NULL,
    `tax_number` VARCHAR(191) NULL,
    `_address` VARCHAR(191) NULL,
    `phone` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `logo_url` VARCHAR(191) NULL,

    UNIQUE INDEX `ORGANIZATION_tax_number_key`(`tax_number`),
    UNIQUE INDEX `ORGANIZATION_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORGANIZATION_DOC_TYPE` (
    `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `type_name` VARCHAR(191) NOT NULL,
    `type_name_ar` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORGANIZATION_DOCUMENT` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `org_id` INTEGER NOT NULL,
    `doc_type_id` TINYINT UNSIGNED NOT NULL,
    `file_url` VARCHAR(191) NOT NULL,
    `file_size_bytes` INTEGER NOT NULL,
    `is_verified` BOOLEAN NOT NULL DEFAULT false,
    `verified_by` INTEGER NULL,
    `verified_at` DATETIME(3) NULL,
    `rejection_reason` TEXT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORGANIZATION_STATUS` (
    `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `status_name` VARCHAR(191) NOT NULL,
    `status_name_ar` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORGANIZATION_STATUS_HISTORY` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `org_id` INTEGER NOT NULL,
    `old_status_id` TINYINT UNSIGNED NOT NULL,
    `new_status_id` TINYINT UNSIGNED NOT NULL,
    `changed_by` INTEGER NOT NULL,
    `reason` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORGANIZATION_TYPE` (
    `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `_name` VARCHAR(191) NOT NULL,
    `_name_ar` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PERMISSION` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `permission_code` VARCHAR(191) NOT NULL,
    `permission_name` VARCHAR(191) NOT NULL,
    `permission_name_ar` VARCHAR(191) NOT NULL,
    `module` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `PERMISSION_permission_code_key`(`permission_code`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ROLE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `org_type_id` TINYINT UNSIGNED NOT NULL,
    `role_name` VARCHAR(191) NOT NULL,
    `role_name_ar` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ROLE_PERMISSION` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `role_id` INTEGER NOT NULL,
    `permission_id` INTEGER NOT NULL,

    UNIQUE INDEX `ROLE_PERMISSION_role_id_permission_id_key`(`role_id`, `permission_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SYSTEM_CONFIG` (
    `config_key` VARCHAR(191) NOT NULL,
    `config_value` TEXT NOT NULL,
    `description` TEXT NULL,

    PRIMARY KEY (`config_key`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SYSTEM_EMPLOYEE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` INTEGER NOT NULL,
    `employee_code` VARCHAR(191) NOT NULL,
    `department` VARCHAR(191) NOT NULL,
    `hired_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `SYSTEM_EMPLOYEE_user_id_key`(`user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TENDER` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `publisher_org_id` INTEGER NOT NULL,
    `category_id` INTEGER NOT NULL,
    `created_by` INTEGER NOT NULL,
    `status_id` TINYINT UNSIGNED NOT NULL,
    `tender_number` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `description` TEXT NULL,
    `estimated_value` DECIMAL(15, 2) NULL,
    `currency` VARCHAR(191) NOT NULL DEFAULT 'SYP',
    `tender_type` VARCHAR(191) NOT NULL,
    `guarantee_percentage` DECIMAL(5, 2) NULL,
    `guarantee_amount` DECIMAL(15, 2) NULL,
    `publish_date` DATE NULL,
    `closing_date` DATE NULL,
    `bid_opening_date` DATE NULL,
    `execution_period_days` INTEGER NULL,
    `technical_conditions` TEXT NULL,
    `financial_conditions` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `TENDER_tender_number_key`(`tender_number`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TENDER_CATEGORY` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `category_name` VARCHAR(191) NOT NULL,
    `description` TEXT NULL,
    `is_active` BOOLEAN NOT NULL DEFAULT true,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TENDER_DOC_TYPE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type_name` VARCHAR(191) NOT NULL,
    `type_name_ar` VARCHAR(191) NOT NULL,
    `is_required` BOOLEAN NOT NULL DEFAULT false,
    `description` TEXT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TENDER_DOCUMENT` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `tender_id` INTEGER NOT NULL,
    `doc_type_id` INTEGER NOT NULL,
    `uploaded_by` INTEGER NOT NULL,
    `file_url` VARCHAR(191) NOT NULL,
    `file_type` VARCHAR(191) NULL,
    `file_size` INTEGER NULL,
    `uploaded_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TENDER_REPORT` (
    `report_id` INTEGER NOT NULL AUTO_INCREMENT,
    `tender_id` INTEGER NOT NULL,
    `generated_by` INTEGER NOT NULL,
    `report_type` VARCHAR(191) NOT NULL,
    `file_url` VARCHAR(191) NOT NULL,
    `generated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`report_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TENDER_STATUS` (
    `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `status_name` VARCHAR(191) NOT NULL,
    `status_name_ar` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TENDER_STATUS_HISTORY` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `tender_id` INTEGER NOT NULL,
    `old_status_id` TINYINT UNSIGNED NOT NULL,
    `new_status_id` TINYINT UNSIGNED NOT NULL,
    `changed_by` INTEGER NOT NULL,
    `reason` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `org_id` INTEGER NOT NULL,
    `role_id` INTEGER NOT NULL,
    `status_id` TINYINT UNSIGNED NOT NULL,
    `f_name` VARCHAR(191) NOT NULL,
    `l_name` VARCHAR(191) NOT NULL,
    `father_name` VARCHAR(191) NULL,
    `national_num` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `phone` VARCHAR(191) NULL,
    `username` VARCHAR(191) NULL,
    `password` VARCHAR(191) NOT NULL,
    `device_token` VARCHAR(191) NULL,

    UNIQUE INDEX `USER_national_num_key`(`national_num`),
    UNIQUE INDEX `USER_email_key`(`email`),
    UNIQUE INDEX `USER_phone_key`(`phone`),
    UNIQUE INDEX `USER_username_key`(`username`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_STATUS` (
    `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `status_name` VARCHAR(191) NOT NULL,
    `status_name_ar` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ACTIVITY_LOG` ADD CONSTRAINT `ACTIVITY_LOG_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `USER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ACTIVITY_LOG` ADD CONSTRAINT `ACTIVITY_LOG_tender_id_fkey` FOREIGN KEY (`tender_id`) REFERENCES `TENDER`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ACTIVITY_LOG` ADD CONSTRAINT `ACTIVITY_LOG_bid_id_fkey` FOREIGN KEY (`bid_id`) REFERENCES `BID`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID` ADD CONSTRAINT `BID_tender_id_fkey` FOREIGN KEY (`tender_id`) REFERENCES `TENDER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID` ADD CONSTRAINT `BID_bidder_org_id_fkey` FOREIGN KEY (`bidder_org_id`) REFERENCES `ORGANIZATION`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID` ADD CONSTRAINT `BID_submitted_by_fkey` FOREIGN KEY (`submitted_by`) REFERENCES `USER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID` ADD CONSTRAINT `BID_status_id_fkey` FOREIGN KEY (`status_id`) REFERENCES `BID_STATUS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID_DOCUMENT` ADD CONSTRAINT `BID_DOCUMENT_bid_id_fkey` FOREIGN KEY (`bid_id`) REFERENCES `BID`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID_DOCUMENT` ADD CONSTRAINT `BID_DOCUMENT_uploaded_by_fkey` FOREIGN KEY (`uploaded_by`) REFERENCES `USER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID_DOCUMENT` ADD CONSTRAINT `BID_DOCUMENT_doc_type_id_fkey` FOREIGN KEY (`doc_type_id`) REFERENCES `BID_DOC_TYPE`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID_EVALUATION` ADD CONSTRAINT `BID_EVALUATION_bid_id_fkey` FOREIGN KEY (`bid_id`) REFERENCES `BID`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID_EVALUATION` ADD CONSTRAINT `BID_EVALUATION_committee_member_id_fkey` FOREIGN KEY (`committee_member_id`) REFERENCES `COMMITTEE_MEMBER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID_GUARANTEE` ADD CONSTRAINT `BID_GUARANTEE_bid_id_fkey` FOREIGN KEY (`bid_id`) REFERENCES `BID`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID_STATUS_HISTORY` ADD CONSTRAINT `BID_STATUS_HISTORY_bid_id_fkey` FOREIGN KEY (`bid_id`) REFERENCES `BID`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID_STATUS_HISTORY` ADD CONSTRAINT `BID_STATUS_HISTORY_old_status_id_fkey` FOREIGN KEY (`old_status_id`) REFERENCES `BID_STATUS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID_STATUS_HISTORY` ADD CONSTRAINT `BID_STATUS_HISTORY_new_status_id_fkey` FOREIGN KEY (`new_status_id`) REFERENCES `BID_STATUS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BID_STATUS_HISTORY` ADD CONSTRAINT `BID_STATUS_HISTORY_changed_by_fkey` FOREIGN KEY (`changed_by`) REFERENCES `USER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMMITTEE` ADD CONSTRAINT `COMMITTEE_tender_id_fkey` FOREIGN KEY (`tender_id`) REFERENCES `TENDER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMMITTEE` ADD CONSTRAINT `COMMITTEE_committee_type_fkey` FOREIGN KEY (`committee_type`) REFERENCES `COMMITTEE_TYPE`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMMITTEE_EVALUATION` ADD CONSTRAINT `COMMITTEE_EVALUATION_bid_id_fkey` FOREIGN KEY (`bid_id`) REFERENCES `BID`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMMITTEE_EVALUATION` ADD CONSTRAINT `COMMITTEE_EVALUATION_committee_id_fkey` FOREIGN KEY (`committee_id`) REFERENCES `COMMITTEE`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMMITTEE_MEMBER` ADD CONSTRAINT `COMMITTEE_MEMBER_committee_id_fkey` FOREIGN KEY (`committee_id`) REFERENCES `COMMITTEE`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMMITTEE_MEMBER` ADD CONSTRAINT `COMMITTEE_MEMBER_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `USER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CONTRACT` ADD CONSTRAINT `CONTRACT_tender_id_fkey` FOREIGN KEY (`tender_id`) REFERENCES `TENDER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CONTRACT` ADD CONSTRAINT `CONTRACT_bid_id_fkey` FOREIGN KEY (`bid_id`) REFERENCES `BID`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NOTIFICATION` ADD CONSTRAINT `NOTIFICATION_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `USER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NOTIFICATION` ADD CONSTRAINT `NOTIFICATION_tender_id_fkey` FOREIGN KEY (`tender_id`) REFERENCES `TENDER`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NOTIFICATION` ADD CONSTRAINT `NOTIFICATION_bid_id_fkey` FOREIGN KEY (`bid_id`) REFERENCES `BID`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORGANIZATION` ADD CONSTRAINT `ORGANIZATION_type_id_fkey` FOREIGN KEY (`type_id`) REFERENCES `ORGANIZATION_TYPE`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORGANIZATION` ADD CONSTRAINT `ORGANIZATION_status_id_fkey` FOREIGN KEY (`status_id`) REFERENCES `ORGANIZATION_STATUS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORGANIZATION_DOCUMENT` ADD CONSTRAINT `ORGANIZATION_DOCUMENT_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `ORGANIZATION`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORGANIZATION_DOCUMENT` ADD CONSTRAINT `ORGANIZATION_DOCUMENT_doc_type_id_fkey` FOREIGN KEY (`doc_type_id`) REFERENCES `ORGANIZATION_DOC_TYPE`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORGANIZATION_DOCUMENT` ADD CONSTRAINT `ORGANIZATION_DOCUMENT_verified_by_fkey` FOREIGN KEY (`verified_by`) REFERENCES `USER`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORGANIZATION_STATUS_HISTORY` ADD CONSTRAINT `ORGANIZATION_STATUS_HISTORY_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `ORGANIZATION`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORGANIZATION_STATUS_HISTORY` ADD CONSTRAINT `ORGANIZATION_STATUS_HISTORY_old_status_id_fkey` FOREIGN KEY (`old_status_id`) REFERENCES `ORGANIZATION_STATUS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORGANIZATION_STATUS_HISTORY` ADD CONSTRAINT `ORGANIZATION_STATUS_HISTORY_new_status_id_fkey` FOREIGN KEY (`new_status_id`) REFERENCES `ORGANIZATION_STATUS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORGANIZATION_STATUS_HISTORY` ADD CONSTRAINT `ORGANIZATION_STATUS_HISTORY_changed_by_fkey` FOREIGN KEY (`changed_by`) REFERENCES `USER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ROLE` ADD CONSTRAINT `ROLE_org_type_id_fkey` FOREIGN KEY (`org_type_id`) REFERENCES `ORGANIZATION_TYPE`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ROLE_PERMISSION` ADD CONSTRAINT `ROLE_PERMISSION_role_id_fkey` FOREIGN KEY (`role_id`) REFERENCES `ROLE`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ROLE_PERMISSION` ADD CONSTRAINT `ROLE_PERMISSION_permission_id_fkey` FOREIGN KEY (`permission_id`) REFERENCES `PERMISSION`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SYSTEM_EMPLOYEE` ADD CONSTRAINT `SYSTEM_EMPLOYEE_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `USER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER` ADD CONSTRAINT `TENDER_publisher_org_id_fkey` FOREIGN KEY (`publisher_org_id`) REFERENCES `ORGANIZATION`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER` ADD CONSTRAINT `TENDER_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `TENDER_CATEGORY`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER` ADD CONSTRAINT `TENDER_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `USER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER` ADD CONSTRAINT `TENDER_status_id_fkey` FOREIGN KEY (`status_id`) REFERENCES `TENDER_STATUS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER_DOCUMENT` ADD CONSTRAINT `TENDER_DOCUMENT_tender_id_fkey` FOREIGN KEY (`tender_id`) REFERENCES `TENDER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER_DOCUMENT` ADD CONSTRAINT `TENDER_DOCUMENT_doc_type_id_fkey` FOREIGN KEY (`doc_type_id`) REFERENCES `TENDER_DOC_TYPE`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER_DOCUMENT` ADD CONSTRAINT `TENDER_DOCUMENT_uploaded_by_fkey` FOREIGN KEY (`uploaded_by`) REFERENCES `USER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER_REPORT` ADD CONSTRAINT `TENDER_REPORT_tender_id_fkey` FOREIGN KEY (`tender_id`) REFERENCES `TENDER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER_REPORT` ADD CONSTRAINT `TENDER_REPORT_generated_by_fkey` FOREIGN KEY (`generated_by`) REFERENCES `USER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER_STATUS_HISTORY` ADD CONSTRAINT `TENDER_STATUS_HISTORY_tender_id_fkey` FOREIGN KEY (`tender_id`) REFERENCES `TENDER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER_STATUS_HISTORY` ADD CONSTRAINT `TENDER_STATUS_HISTORY_old_status_id_fkey` FOREIGN KEY (`old_status_id`) REFERENCES `TENDER_STATUS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER_STATUS_HISTORY` ADD CONSTRAINT `TENDER_STATUS_HISTORY_new_status_id_fkey` FOREIGN KEY (`new_status_id`) REFERENCES `TENDER_STATUS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TENDER_STATUS_HISTORY` ADD CONSTRAINT `TENDER_STATUS_HISTORY_changed_by_fkey` FOREIGN KEY (`changed_by`) REFERENCES `USER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER` ADD CONSTRAINT `USER_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `ORGANIZATION`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER` ADD CONSTRAINT `USER_role_id_fkey` FOREIGN KEY (`role_id`) REFERENCES `ROLE`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER` ADD CONSTRAINT `USER_status_id_fkey` FOREIGN KEY (`status_id`) REFERENCES `USER_STATUS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
