const mongoose = require("mongoose");

const orgs = [
    {
        _id: new mongoose.Types.ObjectId("66b000000000000000000001"),
        org_name: "System",
        _address: "local",
        _type: "SYSTEM",
        phone_number: "099999999",
        email: "admin@admin.com",
        commercial_register_num: "test1",
        commercial_register_date: "2024-01-01",
        license_num: "test1",
        license_date: "2024-01-01",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },
    { // 5
        _id: new mongoose.Types.ObjectId("66b000000000000000000005"),
        org_name: "Future Infrastructure Company",
        _address: "Homs",
        _type: "PUBLISHER",
        phone_number: "099999993",
        email: "info@futureinfrastructure.com",
        commercial_register_num: "CR-10005",
        commercial_register_date: "2023-09-10",
        license_num: "LIC-10005",
        license_date: "2023-10-01",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },
    {
        _id: new mongoose.Types.ObjectId("66b000000000000000000006"),
        org_name: "United Development Corporation",
        _address: "Latakia",
        _type: "PUBLISHER",
        phone_number: "099999994",
        email: "info@uniteddevelopment.com",
        commercial_register_num: "CR-10006",
        commercial_register_date: "2021-11-25",
        license_num: "LIC-10006",
        license_date: "2021-12-10",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },
    {
        _id: new mongoose.Types.ObjectId("66b000000000000000000008"),
        org_name: "National Energy Solutions",
        _address: "Damascus",
        _type: "PUBLISHER",
        phone_number: "099999996",
        email: "info@nationalenergy.com",
        commercial_register_num: "CR-10008",
        commercial_register_date: "2022-05-18",
        license_num: "LIC-10008",
        license_date: "2022-06-01",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },
    {
        _id: new mongoose.Types.ObjectId("66b000000000000000000012"),
        org_name: "Eastern Infrastructure Authority",
        _address: "Homs",
        _type: "PUBLISHER",
        phone_number: "099999988",
        email: "info@easterninfrastructure.com",
        commercial_register_num: "CR-10012",
        commercial_register_date: "2023-01-20",
        license_num: "LIC-10012",
        license_date: "2023-02-01",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },
    {
        _id: new mongoose.Types.ObjectId("66b000000000000000000013"),
        org_name: "National Construction Directorate",
        _address: "Damascus",
        _type: "PUBLISHER",
        phone_number: "099999987",
        email: "info@nationalconstruction.com",
        commercial_register_num: "CR-10013",
        commercial_register_date: "2022-08-12",
        license_num: "LIC-10013",
        license_date: "2022-09-01",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },
    { // 7
        _id: new mongoose.Types.ObjectId("66b000000000000000000003"),
        org_name: "Global Construction Group",
        _address: "Damascus",
        _type: "EXECUTOR",
        phone_number: "099999991",
        email: "info@globalconstruction.com",
        commercial_register_num: "CR-10003",
        commercial_register_date: "2023-03-15",
        license_num: "LIC-10003",
        license_date: "2023-04-01",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },
    {
        _id: new mongoose.Types.ObjectId("66b000000000000000000004"),
        org_name: "Advanced Engineering Solutions",
        _address: "Aleppo",
        _type: "EXECUTOR",
        phone_number: "099999992",
        email: "info@advancedengineering.com",
        commercial_register_num: "CR-10004",
        commercial_register_date: "2022-06-20",
        license_num: "LIC-10004",
        license_date: "2022-07-05",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },
    {
        _id: new mongoose.Types.ObjectId("66b000000000000000000007"),
        org_name: "Modern Building Contractors",
        _address: "Hama",
        _type: "EXECUTOR",
        phone_number: "099999995",
        email: "info@modernbuilding.com",
        commercial_register_num: "CR-10007",
        commercial_register_date: "2024-02-12",
        license_num: "LIC-10007",
        license_date: "2024-03-01",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },
    {
        _id: new mongoose.Types.ObjectId("66b000000000000000000009"),
        org_name: "Reliable Contracting Services",
        _address: "Tartus",
        _type: "EXECUTOR",
        phone_number: "099999997",
        email: "info@reliablecontracting.com",
        commercial_register_num: "CR-10009",
        commercial_register_date: "2023-07-22",
        license_num: "LIC-10009",
        license_date: "2023-08-05",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },
    {
        _id: new mongoose.Types.ObjectId("66b000000000000000000010"),
        org_name: "Damascus Engineering Works",
        _address: "Damascus",
        _type: "EXECUTOR",
        phone_number: "099999998",
        email: "info@damascusengineering.com",
        commercial_register_num: "CR-10010",
        commercial_register_date: "2022-02-10",
        license_num: "LIC-10010",
        license_date: "2022-03-01",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },

    {
        _id: new mongoose.Types.ObjectId("66b000000000000000000011"),
        org_name: "Syrian Industrial Development",
        _address: "Aleppo",
        _type: "EXECUTOR",
        phone_number: "099999989",
        email: "info@syrianindustrial.com",
        commercial_register_num: "CR-10011",
        commercial_register_date: "2021-05-15",
        license_num: "LIC-10011",
        license_date: "2021-06-01",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },
    {
        _id: new mongoose.Types.ObjectId("66b000000000000000000014"),
        org_name: "Modern Infrastructure Solutions",
        _address: "Latakia",
        _type: "EXECUTOR",
        phone_number: "099999986",
        email: "info@moderninfrastructure.com",
        commercial_register_num: "CR-10014",
        commercial_register_date: "2024-01-15",
        license_num: "LIC-10014",
        license_date: "2024-02-01",
        commercial_register:
            "/uploads/organizations/commercial_register/commercial_register.jpg",
        license: "/uploads/organizations/licenses/licenses.jpg",
        logo: "/uploads/logos/logo1.jpg",
    },
];

module.exports = { orgs };
